name: Continuos Deployment workflow

on:
  push:
    branches:
      - main

env:
  HEROKU_API_KEY: ${{secrets.HEROKU.API.KEY}}
  IMAGE_NAME: registry.heroku.com/${{secrets.HEROKU_APP_NAME}}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Heroku Login
        run: heroku container:login
      - name: Build Docker Image
        run: docker build -t ${{env.IMAGE_NAME}} .
      - name: Push Docker Image
        run: docker push ${{env.IMAGE_NAME}}
      - name: Release
      - run: heroku container:release web -a ${{secrets.HEROKU_APP_NAME}}
   
